import { InterfaceIcon } from "./icons";

export function FeatureBarsIcon() {
  return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden><path d="M3 14h4v8H3zM10 8h4v14h-4zM17 2h4v20h-4z" /></svg>;
}
function VisualPill({ children, active = false }: { children: React.ReactNode; active?: boolean }) {
  return <span className={active ? "is-active" : ""}>{children}</span>;
}
export function FeatureVisual({ kind }: { kind: number }) {
  return <div className="pv-feature-art" aria-hidden>
    <div className="pv-art-label">{kind === 1 ? <InterfaceIcon name="pulse" /> : <FeatureBarsIcon />}<span>{["ANÁLISIS PRE-PARTIDO", "ANÁLISIS EN VIVO", "TU PANEL PERSONAL"][kind]}</span><svg viewBox="0 0 16 16" fill="none" className="pv-feature-chevron"><path d="m6 4 4 4-4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></svg></div>
    {kind === 0 ? <div className="pv-feature-probability"><svg className="pv-feature-ring" viewBox="0 0 126 126"><defs><linearGradient id="feature-ring-green" x1="0" y1="1" x2="1" y2="0"><stop stopColor="#8ac32b" /><stop offset=".6" stopColor="#c2f75a" /><stop offset="1" stopColor="#e9ffc0" /></linearGradient></defs><circle cx="63" cy="63" r="55" fill="#0d1917" stroke="#a8e14920" strokeWidth="8" /><circle cx="63" cy="63" r="46" fill="none" stroke="#b8d8c22a" strokeWidth="14" /><circle cx="63" cy="63" r="46" fill="none" stroke="url(#feature-ring-green)" strokeWidth="14" strokeDasharray="196.54 289.03" transform="rotate(-85 63 63)" strokeLinecap="round" /><circle cx="63" cy="63" r="29" fill="#05100e" stroke="#b9ee4580" strokeWidth="2" /><text x="63" y="69" textAnchor="middle" fill="#fff" fontSize="20" fontWeight="750">68%</text></svg><div className="pv-feature-prob-legend">{[{label:"Local",value:68},{label:"Empate",value:22},{label:"Visitante",value:10}].map((row,i)=><div key={row.label}><i className={`pv-feature-dot-${i}`} /><span>{row.label}</span><b>{row.value}%</b></div>)}</div></div> : kind === 1 ? <div className="pv-feature-live-demo"><div className="pv-feature-scoreline"><strong>01</strong><div><span>68′</span><InterfaceIcon name="pulse" /></div><strong>02</strong></div><div className="pv-feature-live-bars">{[9,12,15,13,18,20,13,15,9,12,18,25,15,13,17,25,40].map((height,index)=><i key={index} style={{height}} className={index > 8 ? "is-green" : ""} />)}</div></div> : <div className="pv-feature-dashboard-demo"><span className="pv-feature-growth">+24.8%</span><svg viewBox="0 0 280 119" preserveAspectRatio="none"><defs><linearGradient id="feature-balance-green" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#bcf655" /><stop offset="1" stopColor="#76bb2130" /></linearGradient></defs>{[24,51,78,105].map((y,i)=><g key={y}><text x="0" y={y+3} fill="#7c8c91" fontSize="10">{[60,30,0,-30][i]}</text><path d={`M23 ${y} H276`} stroke="#92a9a22a" strokeDasharray="4 4" /></g>)}{[18,26,33,43,30,39,57,51,68,80].map((height,i)=><rect key={i} x={28+i*25} y={105-height} width="16" height={height} rx="2" fill="url(#feature-balance-green)" opacity={i < 3 ? .4+i*.15 : 1} />)}</svg></div>}
    <div className="pv-art-pills">{kind === 0 ? <><VisualPill active><InterfaceIcon name="target" />Probabilidad</VisualPill><VisualPill><svg viewBox="0 0 20 20" fill="none"><path d="M10 3v13M5 17h10M4 6h12M5 6l-3 6h6L5 6Zm10 0-3 6h6l-3-6Z" stroke="currentColor" strokeWidth="1.3" strokeLinejoin="round" /></svg>Cuota justa</VisualPill></> : kind === 1 ? <><VisualPill active><FeatureBarsIcon />Marcador</VisualPill><VisualPill><svg viewBox="0 0 20 20" fill="none"><circle cx="10" cy="10" r="7" stroke="currentColor" strokeWidth="1.5" /><path d="M10 5v5h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></svg>Minuto a minuto</VisualPill></> : <><VisualPill active><FeatureBarsIcon />Balance</VisualPill><VisualPill><b>%</b>ROI</VisualPill><VisualPill><svg viewBox="0 0 20 20" fill="none"><path d="M5 3h10v14H5zM7 6h6M7 9h6M7 12h5" stroke="currentColor" strokeWidth="1.5" /></svg>Historial</VisualPill></>}</div>
  </div>;
}
