import { InterfaceIcon, SportIcon } from "./icons";
import { FeatureBarsIcon } from "./feature-visuals";

const FAQ = [
  { q: "¿Puedo apostar directamente en PickVerde?", a: "No, PickVerde no es una casa de apuestas. Somos una plataforma de análisis y pronósticos deportivos que te brinda información, estadísticas y herramientas para tomar mejores decisiones. Tú realizas las apuestas en la casa de apuestas de tu preferencia." },
  { q: "¿Qué incluye cada pronóstico?", a: "La selección, su probabilidad estimada, el nivel de confianza y una explicación. En el detalle del partido puedes consultar el contexto y los mercados disponibles." },
  { q: "¿Dónde puedo comprobar los resultados?", a: "En Resultados encontrarás el historial público del modelo con pronósticos acertados, fallados, pendientes y anulados. La tasa de acierto se calcula sobre los aciertos y fallos liquidados." },
  { q: "¿Una probabilidad alta garantiza que voy a ganar?", a: "No. Las probabilidades son estimaciones y pueden fallar. El rendimiento pasado no garantiza resultados futuros; considera siempre el riesgo y tu presupuesto." },
  { q: "¿Cómo funciona el acceso gratuito?", a: "Puedes explorar durante 3 días sin tarjeta. Al registrarte obtienes 2 días adicionales. Después puedes consultar el plan mensual Pro en Precios." },
  { q: "¿Qué deportes están disponibles?", a: "Actualmente el análisis se centra en fútbol. Básquetbol, tenis, béisbol y otros deportes están en preparación y todavía no están disponibles." },
  { q: "¿Cómo llevo el control de mis apuestas?", a: "Inicia sesión y abre Mi panel para registrar el importe, la cuota y el resultado de tus apuestas. El panel calcula el balance, ROI y tasa de acierto sobre tus registros." },
  { q: "¿Puedo cancelar mi suscripción?", a: "El plan Pro es mensual y se gestiona a través de Paddle. Puedes cancelar la renovación desde la gestión de tu suscripción, sin permanencia." },
];
function FaqIcon({ index }: { index: number }) {
  if (index === 2) return <FeatureBarsIcon />;
  if (index === 3) return <InterfaceIcon name="shield" />;
  if (index === 5) return <SportIcon sport="football" />;
  return <svg viewBox="0 0 24 24" fill="none" aria-hidden stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{index === 0 ? <><path d="M20 11a8 8 0 0 1-8 8H7l-4 2 1.5-5A8 8 0 1 1 20 11Z" /><path d="M8 10h.01M12 10h.01M16 10h.01" strokeWidth="3" /></> : index === 1 ? <><path d="M5 3h9l5 5v13H5V3Z" /><path d="M14 3v6h5M9 12h6M9 16h6" /></> : index === 4 ? <><circle cx="12" cy="7" r="4" /><path d="M4 21v-2a6 6 0 0 1 6-6h4a6 6 0 0 1 6 6v2" /></> : index === 6 ? <><path d="m9 3-1 3-3 1v3l-2 2 2 2v3l3 1 1 3h6l1-3 3-1v-3l2-2-2-2V7l-3-1-1-3H9Z" /><circle cx="12" cy="12" r="3" /></> : <><rect x="3" y="5" width="18" height="14" rx="2" /><path d="M3 10h18" /></>}</svg>;
}
function Lightning() {
  return <svg viewBox="0 0 24 24" fill="none" aria-hidden><path d="M13 3 5 13h7l-1 8 8-11h-7l1-7Z" stroke="currentColor" strokeWidth="2" strokeLinejoin="round" /></svg>;
}
export function HomeFaq() {
  return <section className="pv-faq pv-faq-scene" aria-labelledby="home-faq-title"><div className="pv-faq-container"><div className="pv-faq-layout"><div className="pv-faq-intro"><p className="pv-faq-kicker">Preguntas frecuentes</p><h2 id="home-faq-title">Todo claro,<br />desde el <span>inicio.</span></h2><p className="pv-faq-description">Resolvemos las dudas más comunes para que puedas empezar y aprovechar al máximo PickVerde.</p><div className="pv-faq-assurances"><div><span><InterfaceIcon name="shield" /></span><p>Información<br />transparente</p></div><div><span><FeatureBarsIcon /></span><p>Datos reales<br />y actualizados</p></div><div><span><Lightning /></span><p>Sin promesas<br />irreales</p></div></div><div className="pv-faq-demo" aria-hidden><div className="pv-faq-player" /><div className="pv-faq-demo-card pv-faq-demo-odds"><i><svg viewBox="0 0 24 24" fill="none"><path d="m5 15 7-7 7 7" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /></svg></i><div><p>Pronóstico</p><strong>2.15</strong><span>Probabilidad 68%</span></div></div><div className="pv-faq-demo-card pv-faq-demo-return"><i><FeatureBarsIcon /></i><div><p>Rendimiento</p><strong>+42% <small>↗</small></strong><span>Ejemplo ilustrativo</span></div></div></div></div><div className="pv-faq-accordion">{FAQ.map((item,index)=><details key={item.q} name="pickverde-faq" open={index === 0}><summary><span className="pv-faq-question-icon"><FaqIcon index={index} /></span><span className="pv-faq-question-text">{item.q}</span><span className="pv-faq-toggle" aria-hidden><svg viewBox="0 0 20 20" fill="none"><path d="M4 10h12M10 4v12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" /></svg></span></summary><div className="pv-faq-answer"><p>{item.a}</p></div></details>)}</div></div><aside className="pv-responsible-summary" aria-labelledby="responsible-summary-title"><span className="pv-faq-responsible-icon"><InterfaceIcon name="shield" /></span><div><h3 id="responsible-summary-title">Juega con responsabilidad</h3><p>Define un presupuesto que puedas permitirte perder, toma pausas y no persigas pérdidas. Usa el análisis como contexto: una probabilidad alta no garantiza un acierto. Apostar debe ser entretenimiento, nunca una fuente de ingresos.</p></div><span className="pv-age">18+</span></aside></div></section>;
}
