import Link from "next/link";
import { InterfaceIcon, SportIcon } from "./icons";
import { FeatureBarsIcon } from "./feature-visuals";

function Arrow() {
  return <svg viewBox="0 0 24 24" fill="none" aria-hidden><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}
function Tick() {
  return <svg viewBox="0 0 20 20" fill="none" aria-hidden><path d="m4 10 4 4 8-8" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}
function Pitch() {
  return <svg className="pv-pricing-pitch" viewBox="0 0 150 240" fill="none" aria-hidden><path d="M35 5h105v75H35zM87.5 5v75M35 20h12v40H35m105-40h-12v40h12" stroke="currentColor" /><circle cx="87.5" cy="42" r="10" stroke="currentColor" /><path d="m58 107 10 29 20 24 32 23M72 147l-8 8m0-8 8 8M37 180l-8 8m0-8 8 8" stroke="currentColor" /><circle cx="49" cy="99" r="8" stroke="currentColor" /><circle cx="108" cy="142" r="7" stroke="currentColor" /><circle cx="105" cy="200" r="7" stroke="currentColor" /></svg>;
}
const PLANS = [
  { kind:"trial", kicker:"Para empezar", title:"Acceso de prueba", price:"$0", note:"3 días sin tarjeta", features:["Acceso a análisis del partido", "Pronósticos pre-partido y en vivo", "Picks del día con explicación", "Consulta el historial del modelo", "Cobertura de ligas disponibles"], cta:"Crear cuenta gratis", href:"/registro" },
  { kind:"pro", kicker:"Para seguir explorando", title:"Plan Pro", price:"$9", note:"Suscripción mensual", features:["Análisis y escaneos ilimitados", "Contexto en vivo", "Panel personal de apuestas", "Explicación de cada pick", "Todas las ligas disponibles", "Soporte prioritario"], cta:"Conocer Pro", href:"/precios" },
  { kind:"total", kicker:"Plan completo · próximamente", title:"Plan Total", price:"$15", note:"Funciones previstas", features:["Todo lo del Plan Pro", "Análisis táctico con IA", "Informes PDF personalizados", "Comparador de jugadores", "Datos históricos completos", "Alertas inteligentes", "Cobertura global de ligas"], cta:"Ver planes disponibles", href:"/precios" },
] as const;
export function HomePlans() {
  return <section className="pv-pricing" aria-labelledby="home-plans-title"><div className="pv-pricing-container"><div className="pv-pricing-layout"><div className="pv-pricing-intro"><span className="pv-pricing-stripes" aria-hidden /><p className="pv-pricing-kicker">A tu ritmo</p><h2 id="home-plans-title">Primero<br />explóralo<span>.</span><br />Luego elige<span>.</span></h2><p className="pv-pricing-description">Conoce las herramientas, el historial y el análisis de tus partidos antes de elegir un plan. Diseñado para análisis deportivo, datos y seguimiento en tiempo real.</p><Link href="/precios" className="pv-pricing-compare">Comparar todos los planes <Arrow /></Link><div className="pv-pricing-benefits"><div><span><FeatureBarsIcon /></span><p>Datos en<br />tiempo real</p></div><div><span><svg viewBox="0 0 24 24" fill="none" aria-hidden><path d="M11 3a9 9 0 1 0 10 10H11V3Z" stroke="currentColor" strokeWidth="1.7" /><path d="M14 2v8h8a9 9 0 0 0-8-8Z" stroke="currentColor" strokeWidth="1.7" /></svg></span><p>Análisis<br />detallado</p></div><div><span><svg viewBox="0 0 24 24" fill="none" aria-hidden><circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="1.7" /><ellipse cx="12" cy="12" rx="4" ry="9" stroke="currentColor" strokeWidth="1.7" /><path d="M3 12h18M5 6.5h14M5 17.5h14" stroke="currentColor" strokeWidth="1.7" /></svg></span><p>Cobertura de<br />múltiples ligas</p></div></div></div><div className="pv-pricing-cards">{PLANS.map(plan=><article key={plan.kind} className={`pv-pricing-card pv-pricing-card-${plan.kind}`}><Pitch />{plan.kind === "total" && <span className="pv-pricing-best"><InterfaceIcon name="crown" />Próximamente</span>}<span className="pv-pricing-stripes" aria-hidden /><p className="pv-pricing-card-kicker">{plan.kicker}</p><h3>{plan.title}</h3><div className="pv-pricing-price"><strong>{plan.price}</strong>{plan.kind !== "trial" && <span>USD / mes{plan.kind === "total" && <small>Precio previsto</small>}</span>}</div><p className="pv-pricing-note">{plan.note}</p><ul>{plan.features.map(feature=><li key={feature}><span><Tick /></span>{feature}</li>)}</ul><Link href={plan.href} className="pv-pricing-cta">{plan.cta}<Arrow /></Link></article>)}</div></div><div className="pv-pricing-proof"><span className="pv-pricing-plus" aria-hidden>+ + + +</span><p><b>Múltiples ligas</b><br />cobertura internacional</p><p>Datos en<br />tiempo real</p><p>Análisis<br />estadístico</p><p>Historial público<br />de pronósticos</p><div className="pv-pricing-leagues" aria-label="Ligas de fútbol"><span><SportIcon sport="football" />Premier<br />League</span><span className="pv-league-laliga">LALIGA</span><span className="pv-league-serie"><b>A</b>SERIE A</span><span className="pv-league-bundesliga">BUNDESLIGA</span><span><SportIcon sport="football" />CHAMPIONS<br />LEAGUE</span></div></div></div></section>;
}
